### ISSUE TITLE
Conda-forge Linux version trails windows

### ISSUE THREAD

**Issue by ashgillman** [conda-forge/dcmstack-feedstock#7]
See: https://anaconda.org/conda-forge/dcmstack

    linux-64  v0.6.2
    win-32  v0.6.2
    win-64  v0.7
    osx-64  v0.7

Whereas when I install via PyPI on Linux I get the latest v0.7. Is this deliberate or a bug?

Cheers,
Ash

**Comment by kastman** [comment]
@ashgillman There were some hiccups with the recipe; v0.8 should be available everywhere now. Thanks,
