### ISSUE TITLE
0.8 has been out on pypi but I do not see it picked up here yet

### ISSUE THREAD

**Issue by yarikoptic** [conda-forge/dcmstack-feedstock#8]
https://pypi.org/project/dcmstack/ has 0.8.0 but I do not see a PR from a lovely regro-cf-autotick-bot  -- may be some configuration isn't yet fully proper to get it picked up automagically?

**Comment by kastman** [comment]
Closed by #9 - 0.8 should be available for heudiconv now.

**Comment by yarikoptic** [comment]
Thank you!
